apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.global.environment }}
    app: django

spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - name: django-web
          image: {{ .Values.django.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_AUTO_SETUP
              value: "1"

            - name: DJANGO_SETTINGS_MODULE
              value: "{{ .Values.django.project }}.settings.{{ .Values.global.environment }}"

            {{- with .Values.postgres }}
            - name: DJANGO_DB_HOST
              value: {{ .service.name | quote }}

            - name: DJANGO_DB_NAME
              value: {{ .database | quote }}
            {{- end }}
