apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - name: django-web
          image: tharising/django-docker:0.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_AUTO_SETUP
              value: "1"

            - name: DJANGO_SETTINGS_MODULE
              value: "BauerDude.settings.development"

            - name: DJANGO_DB_HOST
              value: "postgres-service"
