# Generated by Django 3.1.1 on 2021-03-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('kd_nr', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='The companies actual name and legal entity type, e.g. Wedgetables GmbH.', max_length=100)),
                ('company_short', models.CharField(help_text='Descriptive name of the company, e.g. Wedgetables.', max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=25, unique=True, verbose_name='Telephone Number')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('art_nr', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Artikel Nr.')),
                ('category', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('weight_units', models.FloatField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['art_nr'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('valid_until', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['parent_id'],
            },
        ),
    ]
