# Generated by Django 3.1.1 on 2021-02-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['art_nr'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
